### ISSUE TITLE
banner on every page load (in UK)

### ISSUE THREAD

**Issue by jshwlkr** [umdigital/umich-cookie-consent#2]
I'm browsing (via VPN through the UK) a test environment with the current plugin version installed and I'm seeing the consent banner on every page load. Is that intended?

**Comment by nobleclem** [comment]
Is that after accepting or declining?

We do have UK configured like the EU so the expectation is that the banner would show for those users until they make a selection.

**Comment by jshwlkr** [comment]
Doesn't seem to matter which option I pick, banner keeps returning on a page load.
On Chrome, Firefox, and Safari via macOS 14.4.1.

**Comment by nobleclem** [comment]
Assuming your test environment is not a umich.edu environment I think that is what is causing the issue.  The one trust production script only sets the cookies to the umich.edu domain and not the domain the site is running as.  I don't have a test mode built into this plugin right now.  I was able to confirm this behavior.  I will investigate adding this ability to the plugin.

**Comment by jshwlkr** [comment]
Ah, yes I was not on an umich.edu domain.

**Comment by nobleclem** [comment]
I have released a new version where there is a settings page that you can enable test mode.  This should make the plugin work as expected on non-umich.edu domains.  Enabling this will add a persistent message on the wordpress admin until it is toggled back to production.  This is to help make sure its not in test mode in a production environment.
