### ISSUE TITLE
Undefined array key "domain" on settings page

### ISSUE THREAD

**Issue by babbassp** [umdigital/umich-cookie-consent#4]
Hello, 

On the settings page, I'm getting an undefined array key displayed in the Domain select options.

![Screenshot 2024-05-20 at 4 20 23 PM](https://github.com/umdigital/umich-cookie-consent/assets/37459212/0c957433-93d2-4c93-8346-19aff1b27c92)

Adding `'domain' => ''` to `$_options` in [umich-cookie-consent.php line 61](https://github.com/umdigital/umich-cookie-consent/blob/master/umich-cookie-consent.php#L61) fixed the issue:

```
self::$_options = array_replace_recursive(
    [ 'mode' => 'prod', 'domain' => '' ],
    get_option( 'umich_cc_options' ) ?: []
 );
```

**Comment by nobleclem** [comment]
2.0.6 should fix that.  Let me know if you notice anything else.
